### PR TITLE
Fixed issue that queue list result is not in alphabetical order.

### PR DESCRIPTION
**Pull request by blueww**
Thanks for contribution! Please go through following checklist before sending PR.
Fix  issue: https://github.com/Azure/Azurite/issues/1210

### PR Branch Destination

- For Azurite V3, please send PR to `master` branch.
- For legacy Azurite V2, please send PR to `legacy-dev` branch.

### Always Add Test Cases

Make sure test cases are added to cover the code change.

### Add Change Log

Add change log for the code change in `Upcoming Release` section in `ChangeLog.md`.

### Development Guideline

Please go to CONTRIBUTION.md for steps about setting up development environment and recommended Visual Studio Code extensions.

### CODE REVIEW

**Review by XiaoningLiu — APPROVED** [review]

**Comment by blueww** [comment]
@XiaoningLiu 

There's a table test case failure, looks should not related with my change.
Would you please help to look?
```
1) Shared Access Signature (SAS) authentication
       Operation using SAS should fail if ACL generating the SAS no longer allow the operation, @loki:
     Uncaught StorageError: Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
RequestId:966cfff5-a31e-426e-b64b-df7a007190fa
Time:2022-01-13T01:52:21.660Z
      at Function.StorageServiceClient._normalizeError (node_modules/azure-storage/lib/common/services/storageserviceclient.js:1206:23)
      at TableService.StorageServiceClient._processResponse (node_modules/azure-storage/lib/common/services/storageserviceclient.js:752:50)
      at Request.processResponseCallback [as _callback] (node_modules/azure-storage/lib/common/services/storageserviceclient.js:319:37)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

**Pull request merged**
