### PR TITLE
refactor tests to use Azure-Storage-Node

### PR DESCRIPTION
**Pull request by swissarmykirpan**
https://github.com/Azure/Azurite/issues/53 - link to the issue

### CODE REVIEW

**Comment by swissarmykirpan** [comment]
The test failure is because table storage not returning anything when being queried using partitionkey and rowkey - https://github.com/Azure/Azurite/issues/52

**Comment by edwin-huber** [comment]
Interestingly, I can't reproduce the error that you and the travis build are reporting...

**Comment by edwin-huber** [comment]
OK, found that the  "done" was not inside the callback from the  query. I'm looking into why we are not returning anything. Once fixed, I shall merge this.

**Comment by edwin-huber** [comment]
hi @swissarmykirpan , the test should look something like this, but our table API needs quite a bit of work to return the correct values.
I'm working on getting it straightened out.
Thanks for your patience!

```javascript
    describe('GET Table Entity', () => {
        it('should retrieve one entity based on the PartitionKey and RowKey of testEntity 1, using OData Metadata None', (done) => {
            tableService.retrieveEntity(tableName, partitionKey, rowKey1, {payloadFormat:"application/json;odata=nometadata"},function (error, result, response) {
                console.log("RESUILT : # " , JSON.stringify(result));
                expect(result['PartitionKey']._).to.equal(partitionKey);
                expect(result['RowKey']._).to.equal(rowKey1);
                expect(result['description']._).to.equal(entityDescription1);
                expect(result['dueDate']._).to.equal(new Date(Date.UTC(2018, 12, 25)).toISOString().split('.')[0]+"Z" );
                done();
            });
        });
```

**Comment by XiaoningLiu** [comment]
@edwin-huber 

@jiacfan has made the change and planned a release including this these days. : )

**Pull request closed without merging**
