### PR TITLE
Bump tedious from 16.0.0 to 16.7.0

### PR DESCRIPTION
**Pull request by WillStephen**
This PR bumps the [tedious](https://www.npmjs.com/package/tedious) version from 16.0.0 to 16.7.0. Version 16.0.0 introduces a [vulnerability](https://cwe.mitre.org/data/definitions/1333.html) which is fixed in 16.7.0.

### CODE REVIEW

**Comment by WillStephen** [comment]
> @WillStephen please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by blueww** [comment]
@XiaoningLiu , @EmmaZhu 
Do you have any comments for this dependecy upgrade?

@WillStephen 
I see the PR is in draft status, do you have pending change for this PR?

**Comment by WillStephen** [comment]
Hi @blueww, sorry for the late reply, I kept it in draft as initially one of the checks was failing, and I thought I'd come back and figure it our when I had more time. I see that everything is passing now - maybe there was some temporary issue with the build machine when I initially ran it. I've moved the PR out of draft status now. Thanks.

**Review by blueww — APPROVED** [review]

**Pull request merged**
