### PR TITLE
Simplify README by exporting subsections into dedicated documentation folder

### PR DESCRIPTION
**Pull request by maxisl**
Reduces README from 1000+ lines to <200 by extracting all subsection that do not need to be on the front page into dedicated subfiles.
All subfiles are stored in a "documentation" folder.

### CODE REVIEW

**Comment by edwin-huber** [comment]
@blueww @XiaoningLiu as discussed, this is the doc update I asked our intern to do.

**Comment by edwin-huber** [comment]
It has uncovered some topics which we need to update.
I suggest updating the docs once we have merged this restructuring.

**Comment by blueww** [comment]
@maxisl , @edwin-huber 

Thanks for the PR!
We need time to test the impact on Docker/Npm/VSC readme page, since part of the link is relative path, to see if we need to change it to absolute path.
And we also need to review the doc changes like what should be kept in main page and what should be moved into sub page.

@maxisl 
Could you give a summary of what has been removed from the doc, and what has been added (besides move the doc to separated doc)? It will help us for the review. Thanks!

**Comment by edwin-huber** [comment]
@blueww I shall provide more details and provide necessary corrections.

**Comment by edwin-huber** [comment]
We need to validate behavior for:
- NPM
  - Should support relative links, if repository is correctly configured.
  - https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository
- Visual Studio Code Extension
  - Needs testing
- Docker
  - Has a separate Readme file

**Pull request closed without merging**
