### PR TITLE
Fix class name of QueueSASAuthenticator

### PR DESCRIPTION
**Pull request by TrentCullinan9412**
Fixes issue with class name in #659 

Just getting my feet wet with this project 😄

### CODE REVIEW

**Review by blueww — APPROVED** [review]

**Comment by blueww** [comment]
@XiaoningLiu 
Would you please help to see if any comments?

**Review by XiaoningLiu — APPROVED** [review]

**Comment by XiaoningLiu** [comment]
Looks good!

It's surprised to me that why exiting code works with wrong class name.

**Pull request merged**
