### PR TITLE
Support production-style URLs (e.g. http://account.localhost/container)

### PR DESCRIPTION
**Pull request by ayeltsov**
Solves #403 - adds ability to use production-style URLs when using "account.localhost" as the host name.
E.g. default URL format for emulator is

> http://hostname[:port]/account/container

this adds ability to use 

> http[s]://account.localhost[:port]/container

It's users' responsibility that account.localhost resolves to 127.0.0.1. On Windows (I believe this works out of the box on Linux), this can be achieved by adding hosts file record, for example. 

C:\Windows\System32\drivers\etc\hosts
```
<...>
127.0.0.1       devstoreaccount1.localhost

```

I contemplated putting this functionality under some sort of flag (like environmental variable).
But then I realized that it's very unlikely to break any existing use patterns, as it requires issuing API requests to accountname.localhost, and having that resolve to 127.0.0.1, hence I proposed to enable this feature by default.

### CODE REVIEW

**Comment by blueww** [comment]
@ayeltsov 
It seems only blob is supported.
Would you like to also add support for queue, and add related cases?

**Comment by ayeltsov** [comment]
I'm going to work on this a bit more.
- tests
- documentation
- Some configuration options:
  - add custom domain name (for example, if someone wants to mock .blob.core.windows.net, they should be able to do this)
  - also considering to add option to any domain suffix (e.g. http[s]://account.*/container

**Comment by XiaoningLiu** [comment]
> I'm going to work on this a bit more.
> 
> * tests
> * documentation
> * Some configuration options:
>   
>   * add custom domain name (for example, if someone wants to mock .blob.core.windows.net, they should be able to do this)
>   * also considering to add option to any domain suffix (e.g. http[s]://account.*/container

Hi @ayeltsov, I'd like to merge this PR for v3.6.0 planned in this week. Also looking forward to the further more updates mentioned! You can have another PR for that. Using GitHub issue #403 tracking this.

So . You can have the further updates

**Comment by ayeltsov** [comment]
To be honest, I think I have initiated pull a bit prematurely. 
It worked for my limited scenario, but when I started experimenting with Storage Explorer, I noticed that for "localhost" endpoint suffix (e.g. AccountName=mystorage;AccountKey=TXlLZXk=;EndpointSuffix=localhost;DefaultEndpointsProtocol=http;), it sends requests to mystorage.blob.localhost:80

I did not account for that in my change.
I don't think we have to undo the change - it is benign - but I will definitely need to improve on it.

Thanks!

**Pull request merged**
