### PR TITLE
Add CodeQL security scanning

### PR DESCRIPTION
**Pull request by jhutchings1**
Hi, I'm a PM on the GitHub security team. This repository is eligible to try the new [GitHub Advanced Security code scanning](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) beta.

Code scanning runs a static analysis tool called CodeQL which scans your code at build time to find any potential security issues. We've tuned the set of queries to be only the most severe, most precise issues. We'll show alerts in the security tab, and we'll show alerts for any net new vulnerabilities on pull requests as well. We've tried to make this super developer friendly, but we'd love your feedback as we work through the beta. 

If you're interested in trying it out, you can merge this pull request to set up the Actions workflow.

### CODE REVIEW

**Comment by jhutchings1** [comment]
This one should be good to go if you're happy with it. The build is working in my fork.

**Comment by blueww** [comment]
@jhutchings1 
Thanks for raising the PR!
Several questions:
1. How long will CodeQL  runs? Just to want to will it make the develop process be slower.
2. What kind of issue will be found by CodeQL , how will it reported, and how should we handle it?

**Comment by jhutchings1** [comment]
@blueww Thanks for having a look

> 1. How long will CodeQL  runs? Just to want to will it make the develop process be slower.

The build took 5m 27s. That's currently faster than your existing test run, so your developers wouldn't notice since it runs in parallel. 

> 2. What kind of issue will be found by CodeQL , how will it reported, and how should we handle it?

CodeQL is configured to find security vulnerabilities. After the first run, you'll see results in the Security tab for your repo. These are visible to folks with write permissions. You'll also see information about any new vulnerabilities in your Checks for pull requests, so you can make sure that new vulnerabilities don't make it into your code. I'd recommend that you treat any of the alerts as real, and try to fix them. If it's in test code, or is a false positive, you can close the alert by providing that reason, however.

**Comment by blueww** [comment]
@jhutchings1 

Thanks for the detail! I am good for this PR.

@XiaoningLiu 
Would you please help to look, if you are also good with it, we can merge it.

**Pull request merged**
