### PR TITLE
Javascript to typescript

### PR DESCRIPTION
**Pull request by swissarmykirpan**
This PR is the first stage to moving towards TS.
I have converted all the require statements to imports and, exports to follow the ES6 convention, followed by executing Azurite using ts-node.
@edwin-huber @XiaoningLiu 

Fixes - https://github.com/Azure/Azurite/issues/50

### CODE REVIEW

**Comment by edwin-huber** [comment]
Hi @swissarmykirpan , many thanks for this contribution!  
We have some other important merges for testing using the azure-storage package.
Once those are through, I shall look at merging this, and validating with the new tests.  

Kind regards,  

Edwin

**Comment by edwin-huber** [comment]
I should add  that we will need to discuss a move to TS with the core team members, but  I don't see it being too much of a problem.

**Comment by swissarmykirpan** [comment]
Yup no worries @edwin-huber :)

**Comment by edwin-huber** [comment]
Hi @swissarmykirpan ,

you are submitting a lot of changes in a single pull request.  
Something that is normally best done in close collaboration with the owning team.  

Maybe we could discuss this in a little more detail, before you invest too much time into something that we cannot merge with the project due to the very large number of files being changed?

**Comment by swissarmykirpan** [comment]
@edwin-huber yup this PR just demonstrates the steps, we can always pull apart the commits and bring them in one by one. My suggestion would be just to start with the conversion to es6 and running tests under ts-node and typescript

**Comment by swissarmykirpan** [comment]
the PR is in a state with basic minimal steps to getting everything into typescript, without any tslint rules. The next stage would be to implement some stricter rules.

**Comment by edwin-huber** [comment]
@swissarmykirpan , could you please contact me at edwin.huber@microsoft.com ?
Thanks.

**Pull request closed without merging**
