### PR TITLE
Access storage account with production-style url without special suffix

### PR DESCRIPTION
**Pull request by DSakura207**
This pull request improves changes imported by #416, and completes #403.

I have not added any tests yet, since I am not sure how to test the changes well - testing would involve changing hosts file.

Please provide some advice.

Thank you 😃

### CODE REVIEW

**Comment by blueww** [comment]
@DSakura207 
Would you please sign the CLA?

**Comment by DSakura207** [comment]
@blueww 
Signed.

**Comment by blueww** [comment]
@DSakura207
I see the PR is still in status "draft". Is it ready for review?

**Comment by DSakura207** [comment]
Yes if no more tests are required.
 I have run tests locally and they all passed, but to test the new feature, hosts file has to be changed.
Not sure if

**Comment by DSakura207** [comment]
Sorry, fat finger caused request close.
Host file change is required when testing this new feature. 
All tests passed locally, but I am not sure if it's nessary to add another duplicated set of tests, just to test just a few code lines.

**Review by XiaoningLiu — APPROVED** [review]

**Pull request merged**
