### PR TITLE
Fixes #142 - removes the double quotes

### LINKED ISSUE #142: Quotes around etag value failing Json parsing
### Note: https://github.com/rickle-msft asked me to open issue here.
Issue also discussed here (https://github.com/Azure/azure-storage-java/issues/419)

### Which service(blob, file, queue, table) does this issue concern?

    - Azure Storage service (While experimenting with Azurite blob)

### Which version of the SDK was used?

    - azure-storage-blob
    - 10.3.0

### Quotes around etag value causing problem with Json parsing in Java azure blob library 
```
az storage blob upload -c mappings -n store_mappings.csv -f user_mappings.csv --connection-string 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;'
Finished[#############################################################]  100.0000%
{
  "etag": "\"snXFBAfcscEdTKjoHmpCiWKsKz8\"",
  "lastModified": "2019-01-02T21:49:21+00:00"
}
```

```
[error] Caused by: com.microsoft.rest.v2.RestException: HTTP response has malformed headers
[error] 	at com.microsoft.rest.v2.protocol.HttpResponseDecoder.decode(HttpResponseDecoder.java:68)
[error] 	at com.microsoft.rest.v2.policy.DecodingPolicyFactory$DecodingPolicy.lambda$sendAsync$0(DecodingPolicyFactory.java:34)
[error] 	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:76)
[error] 	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:59)
[error] 	at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
[error] 	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
[error] 	at com.microsoft.rest.v2.http.NettyClient$HttpClientInboundHandler.channelRead(NettyClient.java:865)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[error] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
[error] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[error] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[error] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[error] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[error] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[error] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[error] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[error] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
[error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
[error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
[error] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
[error] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[error] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: com.fasterxml.jackson.databind.JsonMappingException: Failed to decode VALUE_STRING as base64 (MIME-NO-LINEFEEDS): Illegal character '"' (code 0x22) in base64 content
[error]  at [Source: {"date":"Wed, 02 Jan 2019 21:55:15 GMT","content-length":"31","x-ms-version":"2016-05-31","Connection":"keep-alive","x-ms-blob-content-md5":"undefined","x-ms-request-server-encrypted":"false","x-ms-blob-type":"BlockBlob","last-modified":"Wed, 02 Jan 2019 10:58:32 GMT","content-range":"bytes 0-30/31","etag":"\"LjOfgK/d1rTN162pjZZKb9eXKQw\"","content-type":"text/csv; charset=utf-8","accept-ranges":"bytes","x-ms-request-id":"16393210-0ed9-11e9-a716-598540133f93","X-Powered-By":"Express"}; line: 1, column: 152]
```

### PR DESCRIPTION
**Pull request by calvernaz**

### CODE REVIEW

**Comment by XiaoningLiu** [comment]
According to https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-properties

Etag | The ETag contains a value that you can use to perform operations conditionally. See Specifying Conditional Headers for Blob Service Operations for more information. If the request version is 2011-08-18 or newer, the ETag value will be in quotes.
-- | --

**Comment by calvernaz** [comment]
This fix comes from a different thread where is suggested to use the value as it comes from the API. Saying that which `/` are you talking about?

The example below shows us to be problematic.
```{
  "etag": "\"snXFBAfcscEdTKjoHmpCiWKsKz8\"",
  "lastModified": "2019-01-02T21:49:21+00:00"
}```

**Comment by XiaoningLiu** [comment]
Oh, I refer to `\"` and "\". 

```JavaScript
this.httpProps[N.ETAG] = `\"${this.proxy.original.etag}\"`;
```

Should update to:

```JavaScript
this.httpProps[N.ETAG] = `"${this.proxy.original.etag}"`;
```

Instead of:

```JavaScript
this.httpProps[N.ETAG] = this.proxy.original.etag;
```

**Comment by calvernaz** [comment]
I don't think so, I've added a test to try to clarify this:

with your suggestion:
```
this.httpProps[N.ETAG] = `"${this.proxy.original.etag}"`;
```
the result will be:
```
{ 'x-powered-by': 'Express',
  etag: '"OT2jTlaB1mfpx+D2wy4VOcZaM80"',
  'last-modified': 'Tue, 15 Jan 2019 10:53:26 GMT',
  connection: 'close' }
```
and this will be further stringified.

with the update I did after the first submission:

```
this.httpProps[N.ETAG] = `${this.proxy.original.etag}`;
```

the result is:

```
{ 'x-powered-by': 'Express',
  etag: 'H9zIVStdQOFV0zlr1cosG6sxaHg',
  'last-modified': 'Tue, 15 Jan 2019 10:55:21 GMT',
  connection: 'close' }
```

**Comment by XiaoningLiu** [comment]
@calvernaz  Double quotes is expected for ETag. See https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-properties

**Comment by XiaoningLiu** [comment]
`ETag` is a HTTP response header, from storage API version 2011-08-18 or newer, the ETag value will be in quotes.

* Good value with quotes: `"0x8D67C289777331A"`
* Wrong value without quotes: `0x8D67C289777331A` **Is this your proposed?**
* Wrong value Azurite currently returned: `\"0x8D67C289777331A\"`

image

**Comment by XiaoningLiu** [comment]
This is a request against storage service instead of Azurite, same quotes like Azurite response.

```bash
xiaoning@Azure:~$ az storage blob upload -c cont1958530 -n cont1958530 -f polyfill.js --connection-string 'DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net'
Finished[#############################################################]  100.0000%
{
  "etag": "\"0x8D67C289777331A\"",
  "lastModified": "2019-01-17T03:05:10+00:00"
}
```

**Comment by calvernaz** [comment]
> `ETag` is a HTTP response header, from storage API version 2011-08-18 or newer, the ETag value will be in quotes.
> 
> * Good value with quotes: `"0x8D67C289777331A"`
> * Wrong value without quotes: `0x8D67C289777331A` **Is this your proposed?**
> 
> image
> 
> Following 2 lines have same behavior, so I don't think this line should be changed. (I made a mistake in previous reply, sorry for that).
> 
> ```js
> this.httpProps[N.ETAG] = `\"${this.proxy.original.etag}\"`;
> ```
> 
> ```js
> this.httpProps[N.ETAG] = `"${this.proxy.original.etag}"`;
> ```

I've read the documentation, if the header contains `"` we should apply as it is, but don't double quoted.

**Comment by calvernaz** [comment]
> This is a request against storage service instead of Azurite, same quotes like Azurite response.
> 
> ```shell
> xiaoning@Azure:~$ az storage blob upload -c cont1958530 -n cont1958530 -f polyfill.js --connection-string 'DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net'
> Finished[#############################################################]  100.0000%
> {
>   "etag": "\"0x8D67C289777331A\"",
>   "lastModified": "2019-01-17T03:05:10+00:00"
> }
> ```

This is the bug, if the value is encoded as base64 the bad escaping makes it fail to read the value, not the header  - Valid JSON, bad string as a base64 value.

On the other hand `""whatever_here""` -> The double quotes would make JSON valid.

**Comment by XiaoningLiu** [comment]
Azurite and storage service are responsible for returning an `ETag` header, and the header value is like `"0x8D67C289777331A"`.

It's `az` tool's behavior to transfer headers into a JSON. Because the value has quotes, so in the JSON, the quotes have been escaped to `\"` to make the JSON valid.
```javascript
{
  "etag": "\"0x8D67C289777331A\"",
  "lastModified": "2019-01-17T03:05:10+00:00"
}
```

Everything seems perfect. I don't understand why the JSON is invalid.

**Comment by calvernaz** [comment]
> Azurite and storage service are responsible for returning an `ETag` header, and the header value is like `"0x8D67C289777331A"`.
> 
> It's `az` tool's behavior to transfer headers into a JSON. Because the value has quotes, so in the JSON, the quotes have been escaped to `\"` to make the JSON valid.
> 
> ```js
> {
>   "etag": "\"0x8D67C289777331A\"",
>   "lastModified": "2019-01-17T03:05:10+00:00"
> }
> ```
> 
> Everything seems perfect. I don't understand why the JSON is invalid.

Ok, so there are two potential issues: 

1. Invalid ETag value escaping turning into JSON deserialization problem.
2. Double quotes around the ETag header.

1 - As mentioned in #142 issue. Valid JSON but bad a value caused by the escaping, incorrect base64 encoded the string. Again check the bug related.

```js
{
  "etag": "\"snXFBAfcscEdTKjoHmpCiWKsKz8\"",
  "lastModified": "2019-01-02T21:49:21+00:00"
}
``` 

2. The second is just a variation on your fix proposal where we would remove the escaping. It produces invalid JSON. 

```js
{
  "etag": ""snXFBAfcscEdTKjoHmpCiWKsKz8"",
  "lastModified": "2019-01-02T21:49:21+00:00"
}
``` 

This is not a particular problem with the `az` cli tool, it happens using the client SDK too. And if this isn't enough the same code works against the Azure Blob API and doesn't work against the Azurite.

**Comment by XiaoningLiu** [comment]
I still don't think Azurite should have a change at the etag implementation.

1. Azurite doesn't return JSON for any requests, it's not Azurite's responsibility to make sure a JSON object valid it cannot touch. Azurite just return etag as a header. No matter what header values Azurite returned, it's tool/client/SDKs' job making a valid JSON. 

2. These following 2 lines code will return exactly same string. First line is what Azurite does currently. Second line is my previous proposal, but I should NOT propose that because they are exact the same.

```javascript
this.httpProps[N.ETAG] = `\"${this.proxy.original.etag}\"`;
```
```javascript
this.httpProps[N.ETAG] = `"${this.proxy.original.etag}"`;
```

3. The only difference between Azurite etag with a "real" etag is the value itself.

* Azurite: `"1UABEikqlCWtsbDwu0gJ4L0MYxI"`

* Azure Storage: `"0x8D67C289777331A"`

4. There is no other SDK or tool having the same issue. Storage explorer works just good. 

image

**Pull request closed without merging**
