### PR TITLE
Add OAuth support for Azurite table

### PR DESCRIPTION
**Pull request by zzhxiaofeng**
1. Fix issue https://github.com/Azure/Azurite/issues/945.
2. Updated file list:
- src/table/TableRequestListenerFactory.ts
- src/table/authentication/TableTokenAuthenticator.ts
- src/table/errors/StorageErrorFactory.ts
- src/table/utils/constants.ts
- package.json
- src/table/TableRequestListenerFactory.ts
- src/table/TableServer.ts
- tests/table/apis/table.batch.tests.errorhandling.ts
- tests/table/apis/table.entity.tests.azure.data-tables.ts
- src/table/TableEnvironment.ts
- src/table/main.ts

@jongio, @XiaoningLiu  for notification.

### CODE REVIEW

**Review by XiaoningLiu — COMMENTED** [review]
Thanks for the contribution on Table RBAC! 

Seems updates to "table/main.ts" are missing, please update that file to accept OAuth Table options.

For more backgrounds, there are 3 entries for Azurite Table:
- by "azurite" cmd --> in "azurite.ts"
- by "azurite-table" cmd --> in "table/main.ts"
- by Visual Studio Code extension

**Comment by zzhxiaofeng** [comment]
@XiaoningLiu Ok, I have updated the `table/main.ts` and please have a look when you are free.

**Comment by v-xuto** [comment]
@XiaoningLiu Please review this PR when you are free.

**Comment by XiaoningLiu** [comment]
Hi @zzhxiaofeng @v-xuto As synced in email, can we have some test cases?

**Comment by zzhxiaofeng** [comment]
@XiaoningLiu I have added the test cases before, please have a look when you are free.

**Review by XiaoningLiu — APPROVED** [review]

**Pull request merged**
