### PR TITLE
Bug undefined variable in TableStorageManager fixed

### PR DESCRIPTION
**Pull request by AleF83**

### CODE REVIEW

**Comment by tlycken** [comment]
Ping @arafato! Any chance of merging this (or #15 which is the same fix) soon? I'm seeing this as well, and it would be nice to not have to monkey-patch the code (see #19 for my specific use-case) but just use the docker container as-is :)

**Comment by tlycken** [comment]
@AleF83 I did find https://hub.docker.com/r/daviddriscoll/azurite/ which seems to have this bug fixed, which you could use as a temporary workaround until this merges.

**Comment by edwin-huber** [comment]
Hi @tlycken thanks for your contribution!

I'm just working through a couple of things, and will then be updating the project accordingly.
Please give me a couple days to get everything straight.

**Comment by edwin-huber** [comment]
Changed base to dev branch and merging

**Comment by hgezim** [comment]
When's this expected to make it into a release?

**Pull request merged**
