### PR TITLE
BlockBlob_StageBlock now checks Content-MD5 and errors if there is an MD5-mismatch

### PR DESCRIPTION
**Pull request by wayne-li2**
BlockBlob_StageBlock now checks Content-MD5 and errors if there is an MD5-mismatch.

This PR tackles issue #303 only for BlockBlob_StageBlock.

### CODE REVIEW

**Review by blueww — APPROVED** [review]

**Comment by blueww** [comment]
@XiaoningLiu 
The PR is OK for me.
Do you have any comments?

**Comment by XiaoningLiu** [comment]
It looks good to me and it should work. There is still some space we can do to improve the performance. The implementation now adds additional reading from disk to calculate the md5. Ideally we can do the md5 calculation during the first extentAppend operation on the air. We can reduce one additional disk read. This is an advanced ask, just to check if @wayne-li2 you want to check this? : )

**Comment by wayne-li2** [comment]
@XiaoningLiu I could only spare a brief look today, and am afraid I can't commit to more time right now. Would it be possible to merge this + release a new Docker image? Happy to continue being a contributor in the future!

**Comment by wayne-li2** [comment]
@blueww @XiaoningLiu Bump on this PR? Also, there seems to be a failing check, but looking at the output it is unrelated to any changes in this PR.

**Pull request merged**
