### PR TITLE
Fix flipped parameters, according to docs

### PR DESCRIPTION
**Pull request by ArtemTrofimushkin**
Fix for [issue](https://github.com/Azure/Azurite/issues/629)

### CODE REVIEW

**Comment by ArtemTrofimushkin** [comment]
Hi, @blueww, @XiaoningLiu!
What can I do to make this pull request progress?

**Comment by ArtemTrofimushkin** [comment]
Hi @blueww!
It seems that all pipelines passed.

**Comment by blueww** [comment]
@xiaoning,

Would you please help to look?

**Comment by ArtemTrofimushkin** [comment]
Hi @blueww, @XiaoningLiu !
Any updates on this?

**Comment by edwin-huber** [comment]
@XiaoningLiu @blueww the change makes sense to me...   
But then why do the SDKs all work against the service? 🤷

**Comment by blueww** [comment]
The code change looks good to me. It's better that a change log can be added for the fix in https://github.com/Azure/Azurite/blob/master/ChangeLog.md

**Comment by ArtemTrofimushkin** [comment]
@blueww Sure, changelog updated

**Review by blueww — APPROVED** [review]

**Pull request merged**
