### PR TITLE
Filter by tags

### PR DESCRIPTION
**Pull request by EmmaZhu**
This is an uncompleted PR which is only to show how the basic logic works.
I'll still need to:
1. Add comments on why implementation looks like this.
2. Add support for ifTags condition for all blob operations
3. Add documents about limitation and best practice.
4. Add more cases for testing.
5. Make error report more accurate.

 
Thanks for contribution! Please go through following checklist before sending PR.

### PR Branch Destination

- For Azurite V3, please send PR to `main` branch.
- For legacy Azurite V2, please send PR to `legacy-dev` branch.

### Always Add Test Cases

Make sure test cases are added to cover the code change.

### Add Change Log

Add change log for the code change in `Upcoming Release` section in `ChangeLog.md`.

### Development Guideline

Please go to CONTRIBUTION.md for steps about setting up development environment and recommended Visual Studio Code extensions.

### CODE REVIEW

**Comment by brunobattezzati** [comment]
Hi @blueww  @EmmaZhu, any update about this? 
Is there any way I could help?

**Comment by bbattezzati** [comment]
hi @blueww @EmmaZhu 

I've forked [EmmaZhu:filter_by_tags_tablequeryway] branch and worked on top of it.
I worked on 2 point - support for ifTags condition for all blob operations.

Just submitted another [PR](https://github.com/Azure/Azurite/pull/2372).

**Comment by laurencenairne-work** [comment]
Is this now a dead PR, given it's six months old? Has the plan changed? What does the roadmap for adding endpoints for azure storage look like, because we still appear to be missing quite a bit.

**Comment by EmmaZhu** [comment]
Hi @laurencenairne-work , I'm still work on this, will update progress recently.

**Comment by AlexMunoz** [comment]
Do you need help @EmmaZhu?  We are developing something and we need this feature.

**Comment by AlexMunoz** [comment]
Hello @EmmaZhu I've tested the lastest changes locally and it looks really good! findBlobsByTags works perfectly! Let me know if you need anything else from me to help move this forward.

**Comment by EmmaZhu** [comment]
Hi @AlexMunoz ,

We are trying to get this feature ready, thanks a lot for trying it and sharing your result. It'd be very helpful if you can share which scenario you have tested, and any defects seen. 

Thanks a lot.

**Comment by AlexMunoz** [comment]
Hello @EmmaZhu Our scenario is not complex, we do this:

1. We create a blob and assign 3 tags to it. 

On request:

1. Using findBlobsByTags, we get all the blobs that match one of two specific tags.
2. The resulting blob list is filtered by the values of the extra tag.
3. At the end we download the content of the remaining blobs.

findBlobsByTags was the functionality we needed for local development and the implementation in your PR works for our use case.

**Comment by EmmaZhu** [comment]
Change the filter by blob feature from unsupported to preview

**Comment by EmmaZhu** [comment]
Check SAS permission for filter blob by tags.

**Review by blueww — APPROVED** [review]

**Pull request merged**
