### PR TITLE
Set Blob Tier

### PR DESCRIPTION
**Pull request by suruchimalewar**
Features added:
1. "setBlobTier" functionality for HOT, COOL and Archive at blob level.
2:  Re-hydration for Archive Tier.

Reason:
Azure takes 3-15 hr in case of restoring data form archive tier to HOT tier. And till that time archive is being restore to HOT tier, user should be acknowledge about the status of data.

@arafato   @pmanlukas  @edwin-huber  @XiaoningLiu Can you please review this PR

### CODE REVIEW

**Comment by brpang** [comment]
Any updates on this PR? It would be great to have this feature available soon.

@arafato @pmanlukas @edwin-huber @XiaoningLiu

**Comment by dpsi** [comment]
@suruchimalewar Really looking forward to this feature, but using your branch I observe this behaviour:
```
bash-4.4# az storage blob show  --container-name test --name testobj1
Name      Blob Type    Blob Tier    Length    Content Type              Last Modified              Snapshot
--------  -----------  -----------  --------  ------------------------  -------------------------  ----------
testobj1  BlockBlob    ARCHIVE      484       application/octet-stream  2019-02-20T23:49:42+00:00

bash-4.4# az storage blob download  --container-name test --name testobj1 -f /tmp/gg
Finished[#############################################################]  100.0000%
Name      Blob Type    Blob Tier    Length    Content Type              Last Modified              Snapshot
--------  -----------  -----------  --------  ------------------------  -------------------------  ----------
testobj1  BlockBlob                 484       application/octet-stream  2019-02-20T23:49:42+00:00
```

I would expect a 409 to be returned when GETing a blob with tier Archive.

**Comment by suruchimalewar** [comment]
@dpsi thanks for sanity.
Could you please elaborate your scenario so that i can check.

**Comment by dpsi** [comment]
```
$ az storage container create --name 'test' --connection-string 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1[179/179]KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;'
{
  "created": true
}

$ az storage blob upload --container-name 'test' --connection-string 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFP
TOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;' --name testobj --file myfile
Finished[#############################################################]  100.0000%
{
  "etag": "\"NG6Bu/nzaI/8RwnY3dYLB2KpoNI\"",
  "lastModified": "2019-02-22T03:15:17+00:00"
}

$ az storage blob show --name testobj --container-name 'test' --connection-string 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErC
z4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;'
{
  "content": "",
  "deleted": false,
  "metadata": {},
  "name": "testobj",
  "properties": {
    "appendBlobCommittedBlockCount": null,
    "blobTier": "Hot",
    "blobTierChangeTime": null,
    "blobTierInferred": false,
    "blobType": "BlockBlob",
    "contentLength": 437,
    "contentRange": null,
    "contentSettings": {
      "cacheControl": null,
      "contentDisposition": null,
      "contentEncoding": null,
      "contentLanguage": null,
      "contentMd5": null,
      "contentType": "application/octet-stream"
    },
    "copy": {
      "completionTime": null,
      "id": null,
      "progress": null,
      "source": null,
      "status": null,
      "statusDescription": null
    },
    "creationTime": null,
    "deletedTime": null,
    "etag": "\"NG6Bu/nzaI/8RwnY3dYLB2KpoNI\"",
    "lastModified": "2019-02-22T03:15:17+00:00",
    "lease": {
      "duration": null,
      "state": "available",
      "status": "unlocked"
    },
    "pageBlobSequenceNumber": null,
    "pageRanges": null,
    "remainingRetentionDays": null,
    "serverEncrypted": null
  },
  "snapshot": null
}

$ az storage blob set-tier --tier Archive --name testobj --container-name 'test' --connection-string 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT
50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;'

$ az storage blob show --name testobj --container-name 'test' --connection-string 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErC
z4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;'
{
  "content": "",
  "deleted": false,
  "metadata": {},
  "name": "testobj",
  "properties": {
    "appendBlobCommittedBlockCount": null,
    "blobTier": "ARCHIVE",
    "blobTierChangeTime": null,
    "blobTierInferred": false,
    "blobType": "BlockBlob",
    "contentLength": 437,
    "contentRange": null,
    "contentSettings": {
      "cacheControl": null,
      "contentDisposition": null,
      "contentEncoding": null,
      "contentLanguage": null,
      "contentMd5": null,
      "contentType": "application/octet-stream"
    },
    "copy": {
      "completionTime": null,
      "id": null,
      "progress": null,
      "source": null,
      "status": null,
      "statusDescription": null
    },
    "creationTime": null,
    "deletedTime": null,
    "etag": "\"KRPcbG7LdTVVRsKDO3dsHku2g3s\"",
    "lastModified": "2019-02-22T03:16:40+00:00",
    "lease": {
      "duration": null,
      "state": "available",
      "status": "unlocked"
    },
    "pageBlobSequenceNumber": null,
    "pageRanges": null,
    "remainingRetentionDays": null,
    "serverEncrypted": null
  },
  "snapshot": null
}

$ az storage blob download --name testobj --container-name 'test' --connection-string 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;' --file /tmp/out
Finished[#############################################################]  100.0000%
{
  "content": null,
  "deleted": false,
  "metadata": {},
  "name": "testobj",
  "properties": {
    "appendBlobCommittedBlockCount": null,
    "blobTier": null,
    "blobTierChangeTime": null,
    "blobTierInferred": false,
    "blobType": "BlockBlob",
    "contentLength": 437,
    "contentRange": "bytes 0-436/437",
    "contentSettings": {
      "cacheControl": null,
      "contentDisposition": null,
      "contentEncoding": null,
      "contentLanguage": null,
      "contentMd5": "undefined",
      "contentType": "application/octet-stream"
    },                                                                                                                                                                                                                                           "copy": {
      "completionTime": null,
      "id": null,
      "progress": null,
      "source": null,                                                                                                                                                                                                                              "status": null,
      "statusDescription": null
    },
    "creationTime": null,
    "deletedTime": null,
    "etag": "\"KRPcbG7LdTVVRsKDO3dsHku2g3s\"",
    "lastModified": "2019-02-22T03:16:40+00:00",
    "lease": {
      "duration": null,
      "state": null,
      "status": null
    },
    "pageBlobSequenceNumber": null,
    "remainingRetentionDays": null,
    "serverEncrypted": null
  },
  "snapshot": null
}

```

**Comment by edwin-huber** [comment]
Thanks for this contribution.  
We have our hands full completing phase 1 for the new architecture using typescript for the blob API.  
We definitely want to support as many API features as possible in the emulator, so we shall definitely come back to this.

**Comment by dpsi** [comment]
We've been using this patch but would like to move onto v3. When will Set Blob tier and Rehydrate support be added? Happy to test it.

**Comment by XiaoningLiu** [comment]
Set Blob tier is supported in V3, close this since long time no update.

**Pull request closed without merging**
